env:
  es6: true
  node: true
extends: 'eslint:recommended'
plugins:
  - html
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  consistent-this:
    - error
