#!/bin/bash

# 第一引数を COMMAND に代入
COMMAND=$1

# COMMAND で条件分岐
case $COMMAND in
  start)
    # $HOME/.kadecot で crossbar start する
    # $HOME/.kadecot/.crossbar の設定ファイルが有効になる
    cd $HOME/.kadecot
    export ROOTPASS=`cat /dev/urandom| tr -dc 'A-Za-z0-9'| head -c 20`
    nohup crossbar start > ./logs/out.log 2> ./logs/err.log < /dev/null &
    ;;
  stop)
    pkill -f 'crossbar'
    ;;
  restart)
    pkill -f 'crossbar'
    cd $HOME/.kadecot
    export ROOTPASS=`cat /dev/urandom| tr -dc 'A-Za-z0-9'| head -c 20`
    nohup crossbar start > ./logs/out.log 2> ./logs/err.log < /dev/null &
    ;;
  update)
    echo "Updating Kadecot|JS"
    {
      # git pull する
      cd $HOME/.kadecot
      git pull origin master
      sudo chmod a+x $HOME/.kadecot/kadecot
      # 全てに npm install する
      npm install
      ls -d $HOME/.kadecot/v1/plugins/* | xargs -I{} bash -c 'cd {} && npm install --silent'
    } > /dev/null
    echo "Updated."
    ;;
  uninstall)
    echo "Uninstalling Kadecot|JS"
    {
      sudo rm "$(which kadecot)"
      rm -rf $HOME/.kadecot
    } > /dev/null
    echo "Uninstalled."
    ;;
  *)
    # コマンドが見つからなかったら，ヘルプを表示する
    cat <<'EOL'
Usage:
  kadecot start     : Start kadecot via crossbar.io
  kadecot update    : Update kadecot
  kadecot uninstall : Uninstall kadecot
EOL
    ;;
esac
